[project]
name = "ColorMatch_api"
version = "1.0.0"
description = "package for colormatch api"
dependencies = [
    "flask",
    "numpy",
    "requests",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"